spring.application.name=finance-tracker

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=finance_user
spring.datasource.password=finance_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080

# JWT
jwt.secret=9Fv8LxR2QpA7MZcYdH4K6JmTWeN3sB5U
jwt.expiration-ms=3600000
